<x-app-layout title="{{ $lesson->title }} — AXXER Academy">
<style>
.classroom{display:grid;grid-template-columns:310px minmax(0,1fr);gap:22px;align-items:start}.curriculum{position:sticky;top:20px;max-height:calc(100vh - 40px);overflow:auto;padding:0}.course-summary{padding:22px;background:#101d3a;color:white}.course-summary p{color:#aebcda;font-size:12px;margin:4px 0}.course-summary h2{margin:5px 0 14px;font-size:18px}.progress-track{height:6px;background:#ffffff2b;border-radius:10px}.progress-fill{height:100%;background:#568bff;border-radius:10px}.module-title{padding:15px 17px 8px;font-size:11px;text-transform:uppercase;color:#6f7b91}.lesson-link{display:flex;gap:10px;padding:12px 16px;text-decoration:none;color:#26334d;border-left:3px solid transparent}.lesson-link:hover{background:#f3f6fb}.lesson-link.current{background:#eaf1ff;color:#1559e8;border-left-color:#1559e8}.state{width:22px;height:22px;border:1px solid #cbd3e0;border-radius:50%;display:grid;place-items:center;flex:none;font-size:10px}.completed .state{background:#2da873;color:white;border-color:#2da873}.lesson-label strong,.lesson-label small{display:block}.lesson-label strong{font-size:12px}.lesson-label small{font-size:10px;color:#8993a5;margin-top:3px}.player-card{padding:18px}.player{position:relative;padding-top:56.25%;background:#091329;border-radius:10px;overflow:hidden}.player iframe{position:absolute;inset:0;width:100%;height:100%;border:0}.lesson-info{padding:11px 5px 0}.lesson-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:22px;padding-top:20px;border-top:1px solid #e4e8f0}.push{margin-left:auto}.disabled{opacity:.4;pointer-events:none}.certificate{margin-top:18px;background:#e7f7ef;color:#23754a;border-radius:8px;padding:14px;font-weight:700}.watch-note{font-size:11px;color:#7c8799}@media(max-width:850px){.classroom{grid-template-columns:1fr}.curriculum{position:relative;max-height:340px}.player-card{padding:12px}}
</style>
<a href="{{ route('academy.products.show',$product) }}">← {{ $course->title }}</a>
<div class="classroom" style="margin-top:18px"><aside class="card curriculum"><div class="course-summary"><p>CURSO</p><h2>{{ $course->title }}</h2><div class="progress-track"><div id="sidebar-progress" class="progress-fill" style="width:{{ $courseProgress['percentage'] }}%"></div></div><p><span id="progress-label">{{ $courseProgress['percentage'] }}%</span> concluído</p></div>@foreach($sidebar as $group)<div class="module-title">{{ $group['module']->title }}</div>@foreach($group['lessons'] as $item)<a class="lesson-link {{ $item['current']?'current':'' }} {{ $item['completed']?'completed':'' }}" href="{{ $item['url'] }}"><span class="state">{{ $item['completed']?'✓':($item['current']?'▶':'○') }}</span><span class="lesson-label"><strong>{{ $item['lesson']->title }}</strong><small>{{ $item['duration'] }}</small></span></a>@endforeach @endforeach</aside>
<section class="card player-card"><div class="player"><iframe src="{{ $embedUrl }}" title="{{ $lesson->title }}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div><div class="lesson-info"><p class="muted">{{ $module->title }}</p><h1>{{ $lesson->title }}</h1><p>{{ $lesson->description }}</p><p class="watch-note">Sua posição é salva automaticamente enquanto esta página permanece aberta.</p>@if($lesson->support_material)<a class="btn secondary" href="{{ $lesson->support_material }}" target="_blank" rel="noopener noreferrer">↓ Baixar material complementar</a>@endif<div id="certificate" class="certificate" @if(!$courseProgress['certificate_available']) hidden @endif>✓ Certificado disponível — curso 100% concluído</div><div class="lesson-actions"><a class="btn secondary {{ $previousUrl?'':'disabled' }}" href="{{ $previousUrl??'#' }}">← Aula anterior</a><button id="complete-button" class="btn" type="button" @disabled($progress->isCompleted())>{{ $progress->isCompleted()?'✓ Aula concluída':'✓ Marcar como concluída' }}</button><a class="btn push {{ $nextUrl?'':'disabled' }}" href="{{ $nextUrl??'#' }}">Próxima aula →</a></div></div></section></div>
<script>
(()=>{const endpoint=@json($progressUrl);const token=document.querySelector('meta[name="csrf-token"]').content;const button=document.getElementById('complete-button');let seconds={{ $progress->last_seconds }};let lastTick=Date.now();async function save(done=false,keepalive=false){if(document.visibilityState==='visible')seconds+=Math.max(0,Math.round((Date.now()-lastTick)/1000));lastTick=Date.now();try{const response=await fetch(endpoint,{method:'PUT',keepalive,headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':token},body:JSON.stringify({last_seconds:seconds,completed:done})});if(!response.ok)return;const data=await response.json();if(data.completed){button.textContent='✓ Aula concluída';button.disabled=true;}document.getElementById('progress-label').textContent=data.percentage+'%';document.getElementById('sidebar-progress').style.width=data.percentage+'%';if(data.certificate_available)document.getElementById('certificate').hidden=false;}catch(error){}}button.addEventListener('click',()=>save(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save(false,true);else lastTick=Date.now();});setInterval(()=>{if(document.visibilityState==='visible')save();},15000);window.addEventListener('beforeunload',()=>save(false,true));})();
</script>
</x-app-layout>
